name: SQL Notebook

on: push

jobs:
  build:
    runs-on: windows-2022
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build
      shell: pwsh
      run: |
        Write-Output "Decoding code signing certificate."
        Set-Content -Path certificate.txt -Value '${{ secrets.CODE_SIGNING_CERTIFICATE }}'
        certutil -decode certificate.txt certificate.pfx
        $certificatePath = (Resolve-Path "certificate.pfx").Path
        $certificatePassword = "${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}"

        Write-Output "Finding msbuild."
        $msbuildPath = & vswhere.exe -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        Write-Output "Found msbuild at: $msbuildPath"

        Write-Output "Building x64."
        ps1\Clear-TempFiles.ps1
        ps1\New-Release.ps1 -MsbuildPath $msbuildPath -CertificatePath $certificatePath -CertificatePassword $certificatePassword -Platform x64
        Move-Item src/SqlNotebook/bin/SqlNotebook.msi SqlNotebook-64bit.msi
        Move-Item src/SqlNotebook/bin/SqlNotebook.zip SqlNotebook-64bit.zip

        Write-Output "Building x86."
        ps1\Clear-TempFiles.ps1
        ps1\New-Release.ps1 -MsbuildPath $msbuildPath -CertificatePath $certificatePath -CertificatePassword $certificatePassword -Platform x86
        Move-Item src/SqlNotebook/bin/SqlNotebook.msi SqlNotebook-32bit.msi
        Move-Item src/SqlNotebook/bin/SqlNotebook.zip SqlNotebook-32bit.zip

    - name: Upload x64 MSI
      uses: actions/upload-artifact@v3
      with:
        name: SqlNotebook-x64.msi
        path: SqlNotebook-x64.msi

    - name: Upload x64 ZIP
      uses: actions/upload-artifact@v3
      with:
        name: SqlNotebook-x64.zip
        path: SqlNotebook-x64.zip

    - name: Upload x86 MSI
      uses: actions/upload-artifact@v3
      with:
        name: SqlNotebook-x86.msi
        path: SqlNotebook-x86.msi

    - name: Upload x86 ZIP
      uses: actions/upload-artifact@v3
      with:
        name: SqlNotebook-x86.zip
        path: SqlNotebook-x86.zip
