name: SQL Notebook

on: push

jobs:
  build:
    runs-on: windows-2022
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      shell: pwsh
      run: |
        Write-Output "Decoding code signing certificate."
        Set-Content -Path certificate.txt -Value '${{ secrets.CODE_SIGNING_CERTIFICATE }}'
        certutil -decode certificate.txt certificate.pfx
        $certificatePath = (Resolve-Path "certificate.pfx").Path
        $certificatePassword = "${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}"

        Write-Output "Finding msbuild."
        $msbuildPath = & vswhere.exe -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        Write-Output "Found msbuild at: $msbuildPath"

        Write-Output "Running New-Release.ps1."
        ps1\New-Release.ps1 -MsbuildPath $msbuildPath -CertificatePath $certificatePath -CertificatePassword $certificatePassword

    - name: Upload MSI
      uses: actions/upload-artifact@v3
      with:
        name: SqlNotebook.msi
        path: src/SqlNotebook/bin/SqlNotebook.msi

    - name: Upload ZIP
      uses: actions/upload-artifact@v3
      with:
        name: SqlNotebook.msi
        path: src/SqlNotebook/bin/SqlNotebook.zip
